### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by ADoebeling** [ADoebeling/qrimg.1601.com#1]
![image](https://cloud.githubusercontent.com/assets/10674780/10540818/cd35a5f0-740b-11e5-9948-eb34f8519f2a.png)

**Comment by ADoebeling** [comment]
idee: http://goqr.me/de/api/

**Comment by LBeckX** [comment]
Reminder

**Comment by ADoebeling** [comment]
@mt1601com Gib mal einen Laut, was machen wir damit?
